ANN - CLASSIFICATION

In [48]:
import pandas as pd;
import tensorflow as tf;
import numpy as np;


In [49]:
tf.__version__

'2.12.0'

Part 1 - Pre-Process Data

In [50]:
#Import csv
#assign dependent and independent variables
#Check for missing data in the dataset

dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [51]:
#Encode Categorical Data 

from sklearn.preprocessing import LabelEncoder;
#Gender is label encoded because there is a relationship in this column (male/female)
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])


#Geographical colunm is encoded using OneHotEncoding because there is no relationship between the points
from sklearn.compose import ColumnTransformer;
from sklearn.preprocessing import OneHotEncoder;

ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
print(X)



[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [52]:
#split up the training and test sets
from sklearn.model_selection import train_test_split;
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [53]:
#feature scaling - standardization is used
from sklearn.preprocessing import StandardScaler;
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
#NO FITTING ON TEST TO AVOID INFORMATION LEAKAGE!!!
X_test = sc.transform(X_test)

PART 2 - BUILDING THE ANN

In [54]:
#--Build the ann

#init the artifical neural network 
ann = tf.keras.models.Sequential()

#The input layer is taken from the features (columns) in x

#Hidden layer 1 - number of neurons is up for experimentation.
ann.add(tf.keras.layers.Dense(6, activation="relu"))

#Hidden layer 2 - number of neurons is up for experimentation.
ann.add(tf.keras.layers.Dense(6, activation="relu"))

#Output layer - number of neurons corresponds to the number of output Columns 1 in this case
#output activation function - binary (2, classification): 'sigmoid', non-binary (>2, classification):'softmax', regression: NO ACTIVATION FUNC

ann.add(tf.keras.layers.Dense(1, activation="sigmoid"))


Part 3 - Training the Artificial Neural Network

In [55]:
#---Compile the ANN---
#Optimizer should perform stochastic gradient descent - 'adam' is a good choice. Remember rolling ball
#The optimizer updates the weight to reduce the loss error between the prediction and real result.
#loss - binary: 'binary_crossentropy', non_binary: 'categorical_crossentropy'
ann.compile(optimizer="adam", loss='binary_crossentropy', metrics=["accuracy"])

In [56]:
#--Train the ANN---
#batch_size - number of compared items during training. Default/Recommended 32.
ann.fit(X_train, y_train, batch_size=32, epochs=50)

Epoch 1/50
250/250 [==============================] - 1s 1ms/step - loss: 0.6856 - accuracy: 0.5821
Epoch 2/50
250/250 [==============================] - 0s 1ms/step - loss: 0.5210 - accuracy: 0.7945
Epoch 3/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4608 - accuracy: 0.7972
Epoch 4/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4329 - accuracy: 0.8133
Epoch 5/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4246 - accuracy: 0.8166
Epoch 6/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4183 - accuracy: 0.8217
Epoch 7/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4128 - accuracy: 0.8213
Epoch 8/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4075 - accuracy: 0.8231
Epoch 9/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4007 - accuracy: 0.8256
Epoch 10/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3918 - accuracy: 0.8307

PART 4 - Making predictions/evaluating the performance of the model

In [62]:
#IMPORTANT - USE THE SAME SCALING AS ABOVE, USE SAME HOT ENCODING
#observation in double brackets - 2d array
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 24ms/step
[[False]]
