In [19]:
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt
import tensorflow as tf;

tf.__version__

'2.12.0'

In [20]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)



[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [21]:
from sklearn.model_selection import train_test_split;
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


In [22]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units=6, activation="relu"))
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

ann.add(tf.keras.layers.Dense(units=1))

In [23]:
ann.compile(optimizer="adam", loss="mean_squared_error")

In [24]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 39506.5195 - accuracy: 0.0000e+00
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 293.1175 - accuracy: 0.0000e+00
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 276.4283 - accuracy: 0.0000e+00
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 255.5748 - accuracy: 0.0000e+00
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 231.4509 - accuracy: 0.0000e+00
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 206.8772 - accuracy: 0.0000e+00
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 180.8910 - accuracy: 0.0000e+00
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 155.4275 - accuracy: 0.0000e+00
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 131.3846 - accuracy: 0.0000e+00
Epoch 10/100
240/240 [=============

In [26]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)

y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)

60/60 [==============================] - 0s 874us/step


(array([[431.04],
        [462.01],
        [465.51],
        ...,
        [472.73],
        [439.55],
        [458.73]], dtype=float32),
 array([[431.23],
        [460.01],
        [461.14],
        ...,
        [473.26],
        [438.  ],
        [463.28]]))